export const ADD_QUESTION = 'QUESTION/ADD';
export const GET_QUESTION_DETAIL = 'QUESTION/GET/DETAIL';
export const CHANGE_QUESTION_UPVOTE = 'QUESTION/CHANGE/UPVOTE';
export const ADD_QUESTION_SONCOUNT='QUESTION/ADD/SONCOUNT';